### ISSUE TITLE
Query Regarding Masking

### ISSUE THREAD

**Issue by WorldHellow** [WhereIsAI/BiLLM#14]
Hello, I need to use your work for an NER style task. And I was wondering if the  `LLamaForTokenClassification` and `Qwen2ForTokenClassification` classes are using bi-directional attention or causal masking? 

I am asking this because in the paper [LS-Llama repo](https://github.com/4AI/LS-LLaMA/tree/main) you have two different classes ` UnmaskingLlamaForTokenClassification` (this uses bi-direction) and `LlamaForTokenClassification` which is uni-directional causal masking.

**Comment by SeanLee97** [comment]
hello @WorldHellow , this repo provides bi-directional LLMs. So `XxxForTokenClassification` is all bidirectional. For NER, here is [an example](https://github.com/WhereIsAI/BiLLM?tab=readme-ov-file#ner).
