### ISSUE TITLE
Llama-2-13b

### ISSUE THREAD

**Issue by SGidentification** [WhereIsAI/BiLLM#8]
Hi, how can we use bigger models like Llama-2-13b?

**Comment by SeanLee97** [comment]
hi @SGidentification , just specify the model_name_or_path to `NousResearch/Llama-2-13b-chat-hf`

**Comment by SGidentification** [comment]
It seems that a multi-GPU script for training is needed as I faced a CUDA memory error.

**Comment by SeanLee97** [comment]
@SGidentification try to decrease the batch size.

**Comment by SGidentification** [comment]
I tried as you mentioned and reduced the batch size to 2 but still the same problem, I guess even by reducing the batch size we cannot load big models like llama-2-13b or 70b, do you have any tips for running  the script on multi-gpus mode?

**Comment by SeanLee97** [comment]
You can try to use HuggingFace trainer https://huggingface.co/docs/transformers/trainer. it provides a friendly way to support multiple GPUs running.
